# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: lib/t1_protocol.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class T1ProtocolMessageType(betterproto.Enum):
    START = 0
    HEARTBEAT = 1
    TALK = 2


@dataclass
class T1Protocol(betterproto.Message):
    type: "T1ProtocolMessageType" = betterproto.enum_field(1)
    name: str = betterproto.string_field(2)
    data: str = betterproto.string_field(3)
